package ui;

import java.io.*;
import java.util.Scanner;

import model.Country;
import model.CountryData;

public class Main {
	
	Scanner sc;
	String [] infoString;
	CountryData countryData;
	public static void main(String[] args) {
		
		Main m = new Main();
		m.principalMenu();
	}

	public Main() {
		sc = new Scanner(System.in);
		countryData = new CountryData();
		
	}
	public void principalMenu(){
		int option;
		do {
			System.out.println("Select an option: " + "\n" +
					"1. Register all the countries " + "\n" +
					"2. Use the predeterminated test" + "\n"+
					"0. Exit");
			 option = sc.nextInt();

			 switch (option){
				 case 1:
					 mainMenu();
					 break;
				 case 2:
					 autogenerated();
					 break;


			 }


		}while(option!=0);


	}
	public void autogenerated(){
		String [] firstSplit = loadData().split("-");
		for(String cData: firstSplit){

			String [] secondSplit = cData.split(";");
			Country country = new Country(secondSplit[0], Integer.parseInt(secondSplit[1]), Integer.parseInt(secondSplit[2]), Integer.parseInt(secondSplit[3]), Integer.parseInt(secondSplit[4]), Integer.parseInt(secondSplit[5]), Integer.parseInt(secondSplit[6]));
			countryData.getCountries().add(country);
		}
		printDataMale();
		printDataFemale();
		printSumData();
	}
	
	public void mainMenu() {

		System.out.println("Enter the number of countries that you will register: ");
		int op = sc.nextInt();
		sc.nextLine();
		
		for (int i =0; i<op;i++) {
			System.out.println("Countryname;GoldMaleMedals;SilverMaleMedal;BronzeMaleMedal;GoldFemaleMedals;SilverFemaleMedal;BronzeFemaleMedal");
			String information = sc.nextLine();
			infoString = information.split(";");
			Country object = new Country(infoString[0],Integer.parseInt(infoString[1]),Integer.parseInt(infoString[2]),Integer.parseInt(infoString[3]),Integer.parseInt(infoString[4]),Integer.parseInt(infoString[5]),Integer.parseInt(infoString[6]));
			countryData.getCountries().add(object);			
		}

		printDataMale();
		printDataFemale();
		printSumData();

		
	}



	public void printDataMale() {
		System.out.print("M A S C U L I N O S" + "\n");
		countryData.compareCountry();
		countryData.printDataMale();
		System.out.println("----------");
	}
	
	public void printDataFemale() {
		System.out.println("F E M E N I N O");
		countryData.compareCountryLower();
		countryData.printDataFemale();
		System.out.println("----------");
	}

	private void printSumData() {
		System.out.println("M E D A L L A S       T O T A L E S");
		countryData.sortWithBubble();
		System.out.println("----------");
		System.out.println("M E D A L L A S       T O T A L E S       I N S E R T I O N");
		countryData.sortWithInsertion();
		System.out.println("----------");

	}

	private String loadData(){
		String text="";
		try{

			File file = new File("data/test.txt");
			FileInputStream fis = new FileInputStream(file);
			InputStreamReader isr = new InputStreamReader(fis);
			BufferedReader reader = new BufferedReader(isr);
			String line;

			while((line = reader.readLine())!=null){

				text+=line;

			}
			reader.close();

		}catch (IOException ex){
			ex.printStackTrace();
		}

		return text;
	}



}
